#!/usr/bin/env python3
"""
assign_signatures

Given an NOE spreadhsheet, an HMQC spreadsheet, and a structure, determine
all possible assignments for the signatures
"""

import argparse
import camera.sat as sat
import camera.hmqc as hmqc
import camera.noes as noes
import camera.ground as ground
import camera.params as params
import camera.network as network
import camera.structures as structures


def get_args():
    """
    Parse command line arguments
    """

    # Create a command line argument parser and add arguments to it
    parser = argparse.ArgumentParser(description=__doc__.strip())
    parser.add_argument("hmqc", help="2D peak list (.csv)")
    parser.add_argument("noes", help="NOE spreadsheet (.csv)")
    parser.add_argument("structure", help="predicted NOE file (.json)")
    parser.add_argument("-r", "--radius", type=float, default=10.,
                        help="Maximum noe distance")
    parser.add_argument("--added-radius", type=float, default=12.,
                        help="Maximum noe distance for added methyls")
    parser.add_argument("--short-radius", type=float, default=8.,
                        help="Maximum distance for short range NOES")
    parser.add_argument("--mcs", type=int, default=3,
                        help="Maximum connected component size of the "
                             "symmetrization graph to use in CSP")
    parser.add_argument("-o", "--output", help="Output HMQC CSV file")
    parser.add_argument("--fa", action="store_true", help="force assignments")
    parser.add_argument("--fo", action="store_true", help="force options")

    args = parser.parse_args()

    # Update globals that are set from command line args

    params.RADIUS = args.radius
    params.SHORT_RADIUS = args.short_radius
    params.ADDED_RADIUS = args.added_radius
    params.MAX_COMP_SIZE = args.mcs
    params.FORCE_ASG = args.fa
    params.FORCE_SV = args.fo

    # Return the command line argument namespace
    return args


def main():
    """
    Main method for the script
    """

    # Parse command line arguments for the script
    args = get_args()

    # Read in list of HMQC signatures
    signatures = hmqc.parse_hmqc_file(args.hmqc)

    # Read in list of NOEs
    crosspeaks = noes.parse_noe_file(args.noes)

    # Get possible clusters for each crosspeak and set the reciprocals
    noes.set_clusters(crosspeaks, signatures)
    noes.set_reciprocals(crosspeaks)

    # Ignore any unclusterable crosspeaks
    crosspeaks = [c for c in crosspeaks if c.clusters]

    # Construct an NOE network from the given crosspeaks
    symgraph = network.SymGraph(crosspeaks, False)
    symgraph.histogram()

    # Read in structure
    structure = structures.load_structure(args.structure)

    # Set the assignments and options sets for the signatures
    hmqc.set_assignment(signatures, structure)

    # Set the activity level to components of size <=2
    symgraph.set_activity_level(args.mcs)

    # Check that ground truth is respected
    ground.check_network(symgraph, structure)

    # Enumerate support sets
    formula = sat.ClusteringCSP(signatures, symgraph, structure)
    support = formula.enumerate()

    # Add support sets as features of the signatures
    for s in signatures:
        s.options = support[s]

    # Show the percent nailed
    hmqc.nailed_histogram(signatures, support)

    # Write support sets out to output file
    if args.output:
        hmqc.to_csv(signatures, args.output)


# Run the main method for the script
if __name__ == "__main__":
    main()
